spring.application.name=msMatch
server.port=8086

spring.main.web-application-type=servlet

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/petfinder_match_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Matching
petfinder.match.minimum-score=70.0

# External services
petfinder.clients.pet.base-url=http://localhost:8081
petfinder.clients.pet.connect-timeout-millis=3000
petfinder.clients.pet.response-timeout-millis=5000

petfinder.clients.adopter.base-url=http://localhost:8083
petfinder.clients.adopter.connect-timeout-millis=3000
petfinder.clients.adopter.response-timeout-millis=5000

petfinder.clients.notification.base-url=http://localhost:8084
petfinder.clients.notification.connect-timeout-millis=3000
petfinder.clients.notification.response-timeout-millis=5000

petfinder.clients.shelter.base-url=http://localhost:8082
petfinder.clients.shelter.connect-timeout-millis=3000
petfinder.clients.shelter.response-timeout-millis=5000
